language: node_js
node_js:
  - "10.16.3"
install: npm install
script:
  - npm run build
  - docker build -t tangerine-fe-image .
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker tag tangerine-fe-image $DOCKER_USER/tangerine-fe-image
  - docker push $DOCKER_USER/tangerine-fe-image